"""Key management: Ed25519 signing keys with rotation history.

- Private keys live ONLY in files under keys_dir (chmod 600), never in the
  database and never in code. These are TEST keys for local development.
- Public keys + rotation history live in SQLite (key_registry table) and are
  published via GET /v1/keys so anyone can verify responses offline.
- Purposes: "api_signing" (signs every response) and "issuer"
  (signs attestations recorded via POST /v1/attestations).

Rotation: rotate() generates a fresh keypair, marks the old key retired
(with retired_at) instead of deleting it — old signatures stay verifiable.
"""
import base64
import os
import secrets
from datetime import datetime, timezone

from . import ed25519
from .models import utcnow_iso

PURPOSES = ("api_signing", "issuer")


def _key_id(purpose: str) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    rand = secrets.token_hex(3)
    return f"npc-{purpose}-{stamp}-{rand}"


class KeyRegistry:
    def __init__(self, store, keys_dir: str):
        self.store = store
        self.keys_dir = keys_dir
        os.makedirs(keys_dir, exist_ok=True)

    # -- private key files -------------------------------------------------
    def _priv_path(self, key_id: str) -> str:
        # key_id is generated by _key_id (safe charset); still sanitize.
        safe = "".join(c for c in key_id if c.isalnum() or c in "-_")
        return os.path.join(self.keys_dir, safe + ".seed")

    def _write_seed(self, key_id: str, seed: bytes):
        path = self._priv_path(key_id)
        tmp = path + ".tmp"
        with open(tmp, "wb") as f:
            f.write(seed)
        os.chmod(tmp, 0o600)
        os.replace(tmp, path)

    def _read_seed(self, key_id: str) -> bytes:
        path = self._priv_path(key_id)
        with open(path, "rb") as f:
            seed = f.read()
        if len(seed) != 32:
            raise ValueError(f"corrupt seed file for key {key_id}")
        return seed

    # -- lifecycle ----------------------------------------------------------
    def generate(self, purpose: str) -> dict:
        """Create a new keypair for purpose; it becomes the active key."""
        if purpose not in PURPOSES:
            raise ValueError(f"purpose must be one of {PURPOSES}")
        seed = secrets.token_bytes(32)
        pub = ed25519.publickey(seed)
        key_id = _key_id(purpose)
        self._write_seed(key_id, seed)
        pub_b64 = base64.b64encode(pub).decode()
        self.store.register_key(key_id, purpose, pub_b64, utcnow_iso())
        return {"key_id": key_id, "public_key_b64": pub_b64}

    def rotate(self, purpose: str) -> dict:
        """Rotate = generate a fresh key; the old one retires, never deleted."""
        return self.generate(purpose)

    def active_key_id(self, purpose: str):
        return self.store.active_key_id(purpose)

    def public_key(self, key_id: str):
        b64 = self.store.public_key_b64(key_id)
        return base64.b64decode(b64) if b64 else None

    def sign(self, purpose: str, message: bytes) -> tuple:
        """Sign with the active key for purpose. Returns (key_id, signature)."""
        key_id = self.active_key_id(purpose)
        if not key_id:
            raise RuntimeError(f"no active key for purpose '{purpose}'")
        seed = self._read_seed(key_id)
        return key_id, ed25519.sign(seed, message)

    def verify(self, key_id: str, message: bytes, signature: bytes) -> bool:
        pub = self.public_key(key_id)
        if pub is None:
            return False
        return ed25519.verify(pub, message, signature)

    def ensure_bootstrap(self):
        """Create keys for every purpose that lacks an active key."""
        created = []
        for purpose in PURPOSES:
            if not self.active_key_id(purpose):
                created.append(self.generate(purpose)["key_id"])
        return created

    def publish(self) -> dict:
        """Public key material for GET /v1/keys. No private material."""
        out = {"api_signing": {"current": None, "history": []},
               "issuers": []}
        for r in self.store.all_keys():
            entry = {
                "key_id": r["key_id"],
                "public_key": r["public_key_b64"],
                "algorithm": "Ed25519",
                "status": r["status"],
                "created_at": r["created_at"],
                "retired_at": r["retired_at"],
            }
            if r["purpose"] == "api_signing":
                if r["status"] == "active":
                    out["api_signing"]["current"] = entry
                else:
                    out["api_signing"]["history"].append(entry)
            else:
                out["issuers"].append(entry)
        return out
